###
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
  "username": "mickey",
  "password": "mouse"
}

###
GET http://localhost:3000/api/user
x-access-token:
###
POST http://localhost:3000/api/new/post/no-image
Content-Type: application/json
x-access-token:

{
  "userId": 2,
  "username": "mickey",
  "displayName": "mouse king",
  "avatar": "/images/image-1659819662733.png",
  "textContent": "testasdfasdf"
}

###
GET http://localhost:3000/api/posts
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoibWlja2V5IiwiaWF0IjoxNjY3MjM3NDU5fQ.Ky5w_DuxZUwUarnbAqUc7p3_2D290mKRS56fDCxAA14

###
DELETE http://localhost:3000/api/posts/72
x-access-token:

###
GET http://localhost:3000/api/search/users

###
POST http://localhost:3000/api/likes/2
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoibWlja2V5IiwiaWF0IjoxNjY3MjM3NDU5fQ.Ky5w_DuxZUwUarnbAqUc7p3_2D290mKRS56fDCxAA14

{
  "userId": 4
}

###
GET http://localhost:3000/api/user/likes/4
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoibWlja2V5IiwiaWF0IjoxNjY3MjM3NDU5fQ.Ky5w_DuxZUwUarnbAqUc7p3_2D290mKRS56fDCxAA14
