GET http://localhost:3000/api/auth/sign-in

###
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
  "username": "hillbilly1",
  "password": "password1"
}

###
GET http://localhost:3000/api/users/9


###
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
  "username": "mickey",
  "password": "mouse"
}

###
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInVzZXJuYW1lIjoibWlja2V5IiwiaWF0IjoxNjU5Mzc0NjY0fQ.qfhZKzfminYuEllYPonkVVRIcRHM1fal1i9yjza4394
