###
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
  "username": "mickey",
  "password": "mouse"
}

###
GET http://localhost:3000/api/user
x-access-token:
###
POST http://localhost:3000/api/new/post/no-image
Content-Type: application/json
x-access-token:

{
  "userId": 2,
  "username": "mickey",
  "displayName": "mouse king",
  "avatar": "/images/image-1659819662733.png",
  "textContent": "testasdfasdf"
}

###
GET http://localhost:3000/api/posts
x-access-token:

###
DELETE http://localhost:3000/api/posts/72
x-access-token:
